#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-demo-app
  name: spring-demo-app
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-demo-app
  template:
    metadata:
      labels:
        app: spring-demo-app
    spec:
      containers:
        - image: #@ data.values.image
          name: spring-demo-app
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-demo-app
  name: spring-demo-app
  namespace: backend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-demo-app