#@ load("@ytt:data", "data")
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: #@ "spring-demo-app-{}".format(data.values.gitrevision)
  namespace: default
spec:
  tag: #@ "{}/spring-demo:{}".format(data.values.dockerusername, data.values.gitrevision)
  serviceAccountName: spring-demo-service-account
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://gitlab.com/sanagaraj-pivotal/spring-demo.git
      revision: #@ data.values.gitrevision
