#@ load("@ytt:data", "data")
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: spring-demo-app
  namespace: default
spec:
  tag: #@ "{}/spring-demo".format(data.values.dockerusername)
  serviceAccountName: spring-demo-service-account
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://gitlab.com/sanagaraj-pivotal/spring-demo.git
      revision: 49735737c41fddd64d2ca7c05263d371bf2dae2a
